apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan1000
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "vlannet",
          "vlan": 1000,
          "ipam": {
            "type": "static"
          }
        }
      ]
    }'
