! -*- zebra -*-

!
hostname r10
log file nodeconf/r10/zebra.log
!
debug zebra events
debug zebra rib
!
!
interface eth1
 ipv6 address fcf0:0:5:10::1/127
!
interface eth2
 ipv6 address fcf0:0:6:10::1/127
!
interface eth3
 ipv6 address fcf0:0:10:11::0/127
!
interface eth4
 ipv6 address fd00:0:5::0/127
!
interface lo
 ipv6 address fcff:10::1/32
!
ipv6 forwarding
!
line vty
!
