---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: srv6
  namespace: c9s-srv6
spec:
  deployment:
    filesFromConfigMap:
        r1:
          - filePath: conf/r1/daemons
            configMapName: srv6-r1-files
            configMapPath: conf-r1-daemons
            mode: read
          - filePath: conf/r1/isisd.conf
            configMapName: srv6-r1-files
            configMapPath: conf-r1-isisd.conf
            mode: read
          - filePath: conf/r1/zebra.conf
            configMapName: srv6-r1-files
            configMapPath: conf-r1-zebra.conf
            mode: execute
        r11:
          - filePath: conf/r11/daemons
            configMapName: srv6-r11-files
            configMapPath: conf-r11-daemons
            mode: read
          - filePath: conf/r11/isisd.conf
            configMapName: srv6-r11-files
            configMapPath: conf-r11-isisd.conf
            mode: read
          - filePath: conf/r11/zebra.conf
            configMapName: srv6-r11-files
            configMapPath: conf-r11-zebra.conf
            mode: execute
        r12:
          - filePath: conf/r12/daemons
            configMapName: srv6-r12-files
            configMapPath: conf-r12-daemons
            mode: read
          - filePath: conf/r12/isisd.conf
            configMapName: srv6-r12-files
            configMapPath: conf-r12-isisd.conf
            mode: read
          - filePath: conf/r12/zebra.conf
            configMapName: srv6-r12-files
            configMapPath: conf-r12-zebra.conf
            mode: execute
        r13:
          - filePath: conf/r13/daemons
            configMapName: srv6-r13-files
            configMapPath: conf-r13-daemons
            mode: read
          - filePath: conf/r13/isisd.conf
            configMapName: srv6-r13-files
            configMapPath: conf-r13-isisd.conf
            mode: read
          - filePath: conf/r13/zebra.conf
            configMapName: srv6-r13-files
            configMapPath: conf-r13-zebra.conf
            mode: execute
        r2:
          - filePath: conf/r2/daemons
            configMapName: srv6-r2-files
            configMapPath: conf-r2-daemons
            mode: read
          - filePath: conf/r2/isisd.conf
            configMapName: srv6-r2-files
            configMapPath: conf-r2-isisd.conf
            mode: read
          - filePath: conf/r2/zebra.conf
            configMapName: srv6-r2-files
            configMapPath: conf-r2-zebra.conf
            mode: execute
        r3:
          - filePath: conf/r3/daemons
            configMapName: srv6-r3-files
            configMapPath: conf-r3-daemons
            mode: read
          - filePath: conf/r3/isisd.conf
            configMapName: srv6-r3-files
            configMapPath: conf-r3-isisd.conf
            mode: read
          - filePath: conf/r3/zebra.conf
            configMapName: srv6-r3-files
            configMapPath: conf-r3-zebra.conf
            mode: execute
        r4:
          - filePath: conf/r4/daemons
            configMapName: srv6-r4-files
            configMapPath: conf-r4-daemons
            mode: read
          - filePath: conf/r4/isisd.conf
            configMapName: srv6-r4-files
            configMapPath: conf-r4-isisd.conf
            mode: read
          - filePath: conf/r4/zebra.conf
            configMapName: srv6-r4-files
            configMapPath: conf-r4-zebra.conf
            mode: execute
        r5:
          - filePath: conf/r5/daemons
            configMapName: srv6-r5-files
            configMapPath: conf-r5-daemons
            mode: read
          - filePath: conf/r5/isisd.conf
            configMapName: srv6-r5-files
            configMapPath: conf-r5-isisd.conf
            mode: read
          - filePath: conf/r5/zebra.conf
            configMapName: srv6-r5-files
            configMapPath: conf-r5-zebra.conf
            mode: execute
        r6:
          - filePath: conf/r6/daemons
            configMapName: srv6-r6-files
            configMapPath: conf-r6-daemons
            mode: read
          - filePath: conf/r6/isisd.conf
            configMapName: srv6-r6-files
            configMapPath: conf-r6-isisd.conf
            mode: read
          - filePath: conf/r6/zebra.conf
            configMapName: srv6-r6-files
            configMapPath: conf-r6-zebra.conf
            mode: execute
        r7:
          - filePath: conf/r7/daemons
            configMapName: srv6-r7-files
            configMapPath: conf-r7-daemons
            mode: read
          - filePath: conf/r7/isisd.conf
            configMapName: srv6-r7-files
            configMapPath: conf-r7-isisd.conf
            mode: read
          - filePath: conf/r7/zebra.conf
            configMapName: srv6-r7-files
            configMapPath: conf-r7-zebra.conf
            mode: execute
  naming: non-prefixed
  definition:
    containerlab: |-
          name: srv6
          topology:
            defaults:
              ports: []
            nodes:
              UPF:
                kind: linux
                image: praqma/network-multitool:latest
                ports: []
              gNB1:
                kind: linux
                image: praqma/network-multitool:latest
                ports: []
              gNB2:
                kind: linux
                image: praqma/network-multitool:latest
                ports: []
              r1:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                binds:
                - conf/r1/daemons:/etc/frr/daemons
                - conf/r1/isisd.conf:/etc/frr/isisd.conf
                - conf/r1/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r2:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth4.seg6_enabled=1
                binds:
                - conf/r2/daemons:/etc/frr/daemons
                - conf/r2/isisd.conf:/etc/frr/isisd.conf
                - conf/r2/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r3:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth4.seg6_enabled=1
                binds:
                - conf/r3/daemons:/etc/frr/daemons
                - conf/r3/isisd.conf:/etc/frr/isisd.conf
                - conf/r3/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r4:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                binds:
                - conf/r4/daemons:/etc/frr/daemons
                - conf/r4/isisd.conf:/etc/frr/isisd.conf
                - conf/r4/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r5:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                binds:
                - conf/r5/daemons:/etc/frr/daemons
                - conf/r5/isisd.conf:/etc/frr/isisd.conf
                - conf/r5/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r6:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                binds:
                - conf/r6/daemons:/etc/frr/daemons
                - conf/r6/isisd.conf:/etc/frr/isisd.conf
                - conf/r6/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r7:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                binds:
                - conf/r7/daemons:/etc/frr/daemons
                - conf/r7/isisd.conf:/etc/frr/isisd.conf
                - conf/r7/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r11:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - ip link add link eth3 name eth3.111 type vlan id 111
                - ip link add link eth3 name eth3.112 type vlan id 112
                - ip link add link eth3 name eth3.113 type vlan id 113
                - ip -6 addr add fd00:0:2::/127 dev eth3.111
                - ip -6 addr add fd00:0:2::2/127 dev eth3.112
                - ip -6 addr add fd00:0:2::4/127 dev eth3.113
                - ip link set eth3.111 up
                - ip link set eth3.112 up
                - ip link set eth3.113 up
                binds:
                - conf/r11/daemons:/etc/frr/daemons
                - conf/r11/isisd.conf:/etc/frr/isisd.conf
                - conf/r11/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r12:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - ip link add link eth3 name eth3.121 type vlan id 121
                - ip link add link eth3 name eth3.122 type vlan id 122
                - ip link add link eth3 name eth3.123 type vlan id 123
                - ip -6 addr add fd00:0:3::/127 dev eth3.121
                - ip -6 addr add fd00:0:3::2/127 dev eth3.122
                - ip -6 addr add fd00:0:3::4/127 dev eth3.123
                - ip link set eth3.121 up
                - ip link set eth3.122 up
                - ip link set eth3.123 up
                binds:
                - conf/r12/daemons:/etc/frr/daemons
                - conf/r12/isisd.conf:/etc/frr/isisd.conf
                - conf/r12/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r13:
                kind: linux
                image: avillaseca01/srv6-frr
                binds:
                - conf/r13/daemons:/etc/frr/daemons
                - conf/r13/isisd.conf:/etc/frr/isisd.conf
                - conf/r13/zebra.conf:/etc/frr/zebra.conf
                ports: []
          debug: false
