---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: testacross
  namespace: across-tc32
spec:
  deployment:
    filesFromConfigMap:
        r1:
          - filePath: conf/r1/daemons
            configMapName: testacross-r1-files
            configMapPath: conf-r1-daemons
            mode: read
          - filePath: conf/r1/isisd.conf
            configMapName: testacross-r1-files
            configMapPath: conf-r1-isisd.conf
            mode: read
          - filePath: conf/r1/zebra.conf
            configMapName: testacross-r1-files
            configMapPath: conf-r1-zebra.conf
            mode: execute
        r2:
          - filePath: conf/r2/daemons
            configMapName: testacross-r2-files
            configMapPath: conf-r2-daemons
            mode: read
          - filePath: conf/r2/isisd.conf
            configMapName: testacross-r2-files
            configMapPath: conf-r2-isisd.conf
            mode: read
          - filePath: conf/r2/zebra.conf
            configMapName: testacross-r2-files
            configMapPath: conf-r2-zebra.conf
            mode: execute
        r3:
          - filePath: conf/r3/daemons
            configMapName: testacross-r3-files
            configMapPath: conf-r3-daemons
            mode: read
          - filePath: conf/r3/isisd.conf
            configMapName: testacross-r3-files
            configMapPath: conf-r3-isisd.conf
            mode: read
          - filePath: conf/r3/zebra.conf
            configMapName: testacross-r3-files
            configMapPath: conf-r3-zebra.conf
            mode: execute
        r4:
          - filePath: conf/r4/daemons
            configMapName: testacross-r4-files
            configMapPath: conf-r4-daemons
            mode: read
          - filePath: conf/r4/isisd.conf
            configMapName: testacross-r4-files
            configMapPath: conf-r4-isisd.conf
            mode: read
          - filePath: conf/r4/zebra.conf
            configMapName: testacross-r4-files
            configMapPath: conf-r4-zebra.conf
            mode: execute
        rg:
          - filePath: conf/rg/daemons
            configMapName: testacross-rg-files
            configMapPath: conf-rg-daemons
            mode: read
          - filePath: conf/rg/isisd.conf
            configMapName: testacross-rg-files
            configMapPath: conf-rg-isisd.conf
            mode: read
          - filePath: conf/rg/zebra.conf
            configMapName: testacross-rg-files
            configMapPath: conf-rg-zebra.conf
            mode: execute
        rgnb:
          - filePath: conf/rgnb/daemons
            configMapName: testacross-rgnb-files
            configMapPath: conf-rgnb-daemons
            mode: read
          - filePath: conf/rgnb/isisd.conf
            configMapName: testacross-rgnb-files
            configMapPath: conf-rgnb-isisd.conf
            mode: read
          - filePath: conf/rgnb/zebra.conf
            configMapName: testacross-rgnb-files
            configMapPath: conf-rgnb-zebra.conf
            mode: execute
        ru:
          - filePath: conf/ru/daemons
            configMapName: testacross-ru-files
            configMapPath: conf-ru-daemons
            mode: read
          - filePath: conf/ru/isisd.conf
            configMapName: testacross-ru-files
            configMapPath: conf-ru-isisd.conf
            mode: read
          - filePath: conf/ru/zebra.conf
            configMapName: testacross-ru-files
            configMapPath: conf-ru-zebra.conf
            mode: execute
        rupf:
          - filePath: conf/rupf/daemons
            configMapName: testacross-rupf-files
            configMapPath: conf-rupf-daemons
            mode: read
          - filePath: conf/rupf/isisd.conf
            configMapName: testacross-rupf-files
            configMapPath: conf-rupf-isisd.conf
            mode: read
          - filePath: conf/rupf/zebra.conf
            configMapName: testacross-rupf-files
            configMapPath: conf-rupf-zebra.conf
            mode: execute
  naming: non-prefixed
  definition:
    containerlab: |-
          name: testacross
          topology:
            defaults:
              ports: []
            nodes:
              hgnb-h1:
                kind: linux
                image: praqma/network-multitool:latest
                exec:
                - ip link add link eth1 name eth1.111 type vlan id 111
                - ip -6 addr add fd00:0:2::1/127 dev eth1.111
                - ip -6 route add fd00:0:1::1/127 via fd00:0:2::0
                - ip link set eth1 up
                - ip link set eth1.111 up
                ports: []
              hgnb-h2:
                kind: linux
                image: praqma/network-multitool:latest
                exec:
                - ip link add link eth1 name eth1.112 type vlan id 112
                - ip -6 addr add fd00:0:2::3/127 dev eth1.112
                - ip -6 route add fd00:0:1::3/127 via fd00:0:2::2
                - ip link set eth1 up
                - ip link set eth1.112 up
                ports: []
              hgnb-h3:
                kind: linux
                image: praqma/network-multitool:latest
                exec:
                - ip link add link eth1 name eth1.113 type vlan id 113
                - ip -6 addr add fd00:0:2::5/127 dev eth1.113
                - ip -6 route add fd00:0:1::5/127 via fd00:0:2::4
                - ip link set eth1 up
                - ip link set eth1.113 up
                ports: []
              hupf-h1:
                kind: linux
                image: praqma/network-multitool:latest
                exec:
                - ip link add link eth1 name eth1.111 type vlan id 111
                - ip link add link eth1 name eth1.112 type vlan id 112
                - ip link add link eth1 name eth1.113 type vlan id 113
                - ip -6 addr add fd00:0:1::1/127 dev eth1.111
                - ip -6 addr add fd00:0:1::3/127 dev eth1.112
                - ip -6 addr add fd00:0:1::5/127 dev eth1.113
                - ip -6 route add fd00:0:2::1/127 via fd00:0:1::0
                - ip -6 route add fd00:0:2::3/127 via fd00:0:1::2
                - ip -6 route add fd00:0:2::5/127 via fd00:0:1::4
                - ip link set eth1 up
                - ip link set eth1.111 up
                - ip link set eth1.112 up
                - ip link set eth1.113 up
                ports: []
              r1:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - ip link set eth1 up
                - ip link set eth2 up
                binds:
                - conf/r1/daemons:/etc/frr/daemons
                - conf/r1/isisd.conf:/etc/frr/isisd.conf
                - conf/r1/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r2:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - ip link set eth1 up
                - ip link set eth2 up
                binds:
                - conf/r2/daemons:/etc/frr/daemons
                - conf/r2/isisd.conf:/etc/frr/isisd.conf
                - conf/r2/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r3:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - ip link set eth1 up
                - ip link set eth2 up
                binds:
                - conf/r3/daemons:/etc/frr/daemons
                - conf/r3/isisd.conf:/etc/frr/isisd.conf
                - conf/r3/zebra.conf:/etc/frr/zebra.conf
                ports: []
              r4:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - ip link set eth1 up
                - ip link set eth2 up
                binds:
                - conf/r4/daemons:/etc/frr/daemons
                - conf/r4/isisd.conf:/etc/frr/isisd.conf
                - conf/r4/zebra.conf:/etc/frr/zebra.conf
                ports: []
              rg:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                - ip link set eth1 up
                - ip link set eth2 up
                - ip link set eth3 up
                binds:
                - conf/rg/daemons:/etc/frr/daemons
                - conf/rg/isisd.conf:/etc/frr/isisd.conf
                - conf/rg/zebra.conf:/etc/frr/zebra.conf
                ports: []
              rgnb:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - ip link add link eth2 name eth2.111 type vlan id 111
                - ip link add link eth2 name eth2.112 type vlan id 112
                - ip link add link eth2 name eth2.113 type vlan id 113
                - ip -6 addr add fd00:0:2::/127 dev eth2.111
                - ip -6 addr add fd00:0:2::2/127 dev eth2.112
                - ip -6 addr add fd00:0:2::4/127 dev eth2.113
                - ip link set eth1 up
                - ip link set eth2 up
                - ip link set eth2.111 up
                - ip link set eth2.112 up
                - ip link set eth2.113 up
                binds:
                - conf/rgnb/daemons:/etc/frr/daemons
                - conf/rgnb/zebra.conf:/etc/frr/zebra.conf
                - conf/rgnb/isisd.conf:/etc/frr/isisd.conf
                ports: []
              ru:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth2.seg6_enabled=1
                - sysctl -w net.ipv6.conf.eth3.seg6_enabled=1
                - ip link set eth1 up
                - ip link set eth2 up
                - ip link set eth3 up
                binds:
                - conf/ru/daemons:/etc/frr/daemons
                - conf/ru/isisd.conf:/etc/frr/isisd.conf
                - conf/ru/zebra.conf:/etc/frr/zebra.conf
                ports: []
              rupf:
                kind: linux
                image: avillaseca01/srv6-frr
                exec:
                - service frr start
                - sysctl -p
                - vtysh -c 'configure terminal' -f /etc/frr/zebra.conf
                - vtysh -c 'configure terminal' -f /etc/frr/isisd.conf
                - sysctl -w net.ipv6.conf.eth1.seg6_enabled=1
                - ip link add link eth2 name eth2.111 type vlan id 111
                - ip link add link eth2 name eth2.112 type vlan id 112
                - ip link add link eth2 name eth2.113 type vlan id 113
                - ip -6 addr add fd00:0:1::/127 dev eth2.111
                - ip -6 addr add fd00:0:1::2/127 dev eth2.112
                - ip -6 addr add fd00:0:1::4/127 dev eth2.113
                - ip link set eth1 up
                - ip link set eth2 up
                - ip link set eth2.111 up
                - ip link set eth2.112 up
                - ip link set eth2.113 up
                binds:
                - conf/rupf/daemons:/etc/frr/daemons
                - conf/rupf/zebra.conf:/etc/frr/zebra.conf
                - conf/rupf/isisd.conf:/etc/frr/isisd.conf
                ports: []
          debug: false
