---
apiVersion: v1
kind: ConfigMap
metadata:
  name: across-rupf-files
  namespace: across-tc32
data:
  conf-rupf-daemons: |-
    zebra=yes
    bgpd=no
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    staticd=no
    pbrd=no
    bfdd=no
    fabricd=no

    vtysh_enable=yes
    zebra_options=" -s 90000000 --daemon -A 127.0.0.1"
    bgpd_options="   --daemon -A 127.0.0.1"
    ospfd_options="  --daemon -A 127.0.0.1"
    ospf6d_options=" --daemon -A ::1"
    ripd_options="   --daemon -A 127.0.0.1"
    ripngd_options=" --daemon -A ::1"
    isisd_options="  --daemon -A 127.0.0.1"
    pimd_options="  --daemon -A 127.0.0.1"
    ldpd_options="  --daemon -A 127.0.0.1"
    nhrpd_options="  --daemon -A 127.0.0.1"
    eigrpd_options="  --daemon -A 127.0.0.1"
    babeld_options="  --daemon -A 127.0.0.1"
    sharpd_options="  --daemon -A 127.0.0.1"
    staticd_options="  --daemon -A 127.0.0.1"
    pbrd_options="  --daemon -A 127.0.0.1"
    bfdd_options="  --daemon -A 127.0.0.1"
    fabricd_options="  --daemon -A 127.0.0.1"

  conf-rupf-zebra.conf: |-
    ! -*- zebra -*-

    !
    hostname rupf
    log file nodeconf/rupf/zebra.log
    !
    debug zebra events
    debug zebra rib
    !
    interface eth1
     ipv6 address fd00:0:1::/127
    !
    interface eth2
     ipv6 address fd00:0:4::1/127
    !
    interface lo
     ipv6 address fcff:16::1/32
    !
    ipv6 forwarding
    !
    line vty
    !
