FROM avillaseca01/networkstack:base

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia todos los archivos .py desde el contexto raíz al contenedor
COPY *.py .
COPY tests/test_integration.py .