apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-conf1000
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "vlan",
      "master": "vlannet-k8s",
      "vlanId": 1000,
      "mode": "bridge",
      "ipam": {
        "type": "static",
                "addresses": [ { "address": "10.1.2.200/24" } ],
                "routes": [ { "dst": "10.1.0.0/16", "gw":"10.1.2.1" } ]
      }
    }'
