#!/bin/bash
TOPO_NAME=across
NS=across-tc32

yq() {
  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"
}

PATCH=$(kubectl get deployment r4 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1003\", \"namespace\": \"across-tc32\", \"interface\": \"net1003\"},{\"name\": \"net1008\", \"namespace\": \"across-tc32\", \"interface\": \"net1008\"}]"' -); kubectl patch deployment r4 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r6 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1006\", \"namespace\": \"across-tc32\", \"interface\": \"net1006\"},{\"name\": \"net1009\", \"namespace\": \"across-tc32\", \"interface\": \"net1009\"},{\"name\": \"net1011\", \"namespace\": \"across-tc32\", \"interface\": \"net1011\"}]"' -); kubectl patch deployment r6 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r7 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1004\", \"namespace\": \"across-tc32\", \"interface\": \"net1004\"},{\"name\": \"net1012\", \"namespace\": \"across-tc32\", \"interface\": \"net1012\"}]"' -); kubectl patch deployment r7 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r9 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1007\", \"namespace\": \"across-tc32\", \"interface\": \"net1007\"},{\"name\": \"net1013\", \"namespace\": \"across-tc32\", \"interface\": \"net1013\"},{\"name\": \"net1015\", \"namespace\": \"across-tc32\", \"interface\": \"net1015\"}]"' -); kubectl patch deployment r9 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r3 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1002\", \"namespace\": \"across-tc32\", \"interface\": \"net1002\"},{\"name\": \"net1005\", \"namespace\": \"across-tc32\", \"interface\": \"net1005\"},{\"name\": \"net1007\", \"namespace\": \"across-tc32\", \"interface\": \"net1007\"}]"' -); kubectl patch deployment r3 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r8 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1012\", \"namespace\": \"across-tc32\", \"interface\": \"net1012\"},{\"name\": \"net1013\", \"namespace\": \"across-tc32\", \"interface\": \"net1013\"},{\"name\": \"net1014\", \"namespace\": \"across-tc32\", \"interface\": \"net1014\"}]"' -); kubectl patch deployment r8 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment ru -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net2001\", \"namespace\": \"across-tc32\", \"interface\": \"net2001\"},{\"name\": \"net1014\", \"namespace\": \"across-tc32\", \"interface\": \"net1014\"},{\"name\": \"net1015\", \"namespace\": \"across-tc32\", \"interface\": \"net1015\"}]"' -); kubectl patch deployment ru -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment rupf -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net2001\", \"namespace\": \"across-tc32\", \"interface\": \"net2001\"},{\"name\": \"net2004\", \"namespace\": \"across-tc32\", \"interface\": \"net2004\"}]"' -); kubectl patch deployment rupf -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment ixia-c -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net2004\", \"namespace\": \"across-tc32\", \"interface\": \"net2004\"},{\"name\": \"net2005\", \"namespace\": \"across-tc32\", \"interface\": \"net2005\"}]"' -); kubectl patch deployment ixia-c -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r5 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1008\", \"namespace\": \"across-tc32\", \"interface\": \"net1008\"},{\"name\": \"net1009\", \"namespace\": \"across-tc32\", \"interface\": \"net1009\"},{\"name\": \"net1010\", \"namespace\": \"across-tc32\", \"interface\": \"net1010\"}]"' -); kubectl patch deployment r5 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment rg -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net2002\", \"namespace\": \"across-tc32\", \"interface\": \"net2002\"},{\"name\": \"net1010\", \"namespace\": \"across-tc32\", \"interface\": \"net1010\"},{\"name\": \"net1011\", \"namespace\": \"across-tc32\", \"interface\": \"net1011\"}]"' -); kubectl patch deployment rg -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r1 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1001\", \"namespace\": \"across-tc32\", \"interface\": \"net1001\"},{\"name\": \"net1002\", \"namespace\": \"across-tc32\", \"interface\": \"net1002\"},{\"name\": \"net1003\", \"namespace\": \"across-tc32\", \"interface\": \"net1003\"},{\"name\": \"net1004\", \"namespace\": \"across-tc32\", \"interface\": \"net1004\"}]"' -); kubectl patch deployment r1 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment r2 -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net1001\", \"namespace\": \"across-tc32\", \"interface\": \"net1001\"},{\"name\": \"net1005\", \"namespace\": \"across-tc32\", \"interface\": \"net1005\"},{\"name\": \"net1006\", \"namespace\": \"across-tc32\", \"interface\": \"net1006\"}]"' -); kubectl patch deployment r2 -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get deployment rgnb -n $NS -o yaml | yq '.spec.template.metadata.annotations."k8s.v1.cni.cncf.io/networks" = "[{\"name\": \"net2002\", \"namespace\": \"across-tc32\", \"interface\": \"net2002\"},{\"name\": \"net2005\", \"namespace\": \"across-tc32\", \"interface\": \"net2005\"}]"' -); kubectl patch deployment rgnb -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r1 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1001", "r1:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r1 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1002", "r1:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r1 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1003", "r1:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r1 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1004", "r1:eth4"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r2 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1001", "r2:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r2 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1005", "r2:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r2 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1006", "r2:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r3 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1002", "r3:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r3 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1005", "r3:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r3 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1007", "r3:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r4 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1003", "r4:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r4 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1008", "r4:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r5 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1008", "r5:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r5 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1009", "r5:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r5 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1010", "r5:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r6 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1006", "r6:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r6 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1009", "r6:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r6 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1011", "r6:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r7 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1004", "r7:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r7 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1012", "r7:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r8 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1012", "r8:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r8 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1013", "r8:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r8 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1014", "r8:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r9 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1007", "r9:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r9 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1013", "r9:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.r9 |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1015", "r9:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rg |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net2002", "rg:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rg |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1010", "rg:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rg |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1011", "rg:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.ru |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net2001", "ru:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.ru |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1014", "ru:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.ru |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net1015", "ru:eth3"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rupf |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net2001", "rupf:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rupf |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net2004", "rupf:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rgnb |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net2002", "rgnb:eth1"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.rgnb |= (. | fromjson | .topology.links += [{"endpoints": ["macvlan:net2005", "rgnb:eth2"]}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.ixia-c |= (. | fromjson | .topology.links += [{"type": "macvlan", "endpoint": {"node": "ixia-c", "interface": "eth1", "mac": "02:00:00:00:01:aa"}, "host-interface": "net2004", "mode": "bridge"}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
PATCH=$(kubectl get cm across -n $NS -o yaml | yq '.data.ixia-c |= (. | fromjson | .topology.links += [{"type": "macvlan", "endpoint": {"node": "ixia-c", "interface": "eth2", "mac": "02:00:00:00:01:ff"}, "host-interface": "net2005", "mode": "bridge"}] | tojson)'); kubectl patch cm across -n $NS -o yaml --patch "$PATCH"
kubectl rollout restart deployment r1 -n $NS
kubectl rollout restart deployment r2 -n $NS
kubectl rollout restart deployment r3 -n $NS
kubectl rollout restart deployment r4 -n $NS
kubectl rollout restart deployment r5 -n $NS
kubectl rollout restart deployment r6 -n $NS
kubectl rollout restart deployment r7 -n $NS
kubectl rollout restart deployment r8 -n $NS
kubectl rollout restart deployment r9 -n $NS
kubectl rollout restart deployment rg -n $NS
kubectl rollout restart deployment ru -n $NS
kubectl rollout restart deployment rupf -n $NS
kubectl rollout restart deployment rgnb -n $NS
kubectl rollout restart deployment ixia-c -n $NS
