apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkstack
  namespace: across-tc32
spec:
  selector:
    matchLabels:
      app: networkstack
  template:
    metadata:
      labels:
        app: networkstack
    spec:
      containers:
      - name: networkstack
        image: avillaseca01/networkstack
        env:
        - name: S3_ENDPOINT
          value: "http://138.4.21.162:9000"
        - name: S3_ACCESS_KEY
          value: "URO98YQMXCZaXtsOzU5j"
        - name: S3_SECRET_KEY
          value: "toACdMGyHB9DUktr8qNlgFG1TDOtl8gWC46FpFPW"
        - name: S3_API
          value: "s3v4"
        - name: S3_PATH
          value: "auto"
        - name: S3_BUCKET
          value: "test-experiment"
        - name: ENERGYAWARE
          value: "false"
        volumeMounts:
        - name: networkinfo-volume
          mountPath: /app/networkinfo.json
          subPath: networkinfo.json
        command: ["python3", "-u", "/app/pce.py"]
      volumes:
      - name: networkinfo-volume
        configMap:
          name: networkinfo
