networks:
  kafka_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  zookeeper:
    image: digitalwonderland/zookeeper
    container_name: zookeeper
    networks:
      kafka_network:
        ipv4_address: 172.20.0.5
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      kafka_network:
        ipv4_address: 172.20.0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
    depends_on:
      - zookeeper
    # https://search.maven.org/remotecontent?filepath=org/mongodb/kafka/mongo-kafka-connect/1.15.0/mongo-kafka-connect-1.15.0-all.jar
    
  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    networks:
      kafka_network:
        ipv4_address: 172.20.0.3
    depends_on:
      - kafka
      - influxdb
    environment:
      - KAFKA_BROKER_URL=172.20.0.2:9092
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUX_TOKEN=KijhTmk92TWfg19BhKSMpmSTHzFmpM19e9xMjRHhl63iTAl_2MRTpXGD0_uWWVbiqypf_Zod3yH-JOJGQ_DDaw==
    restart: always
    command: telegraf --config http://influxdb:8086/api/v2/telegrafs/0e60737fd296f000

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    networks:
      kafka_network:
        ipv4_address: 172.20.0.4
    ports:
      - "8086:8086"
    depends_on:
      - kafka
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=giros
      - DOCKER_INFLUXDB_INIT_BUCKET=across
  
  src:
    image: avillaseca01/src
    container_name: src
    networks:
      kafka_network:
        ipv4_address: 172.20.0.7
    tty: true
    stdin_open: true
    volumes:
      - ./src/Docker:/app  

  minio:
    image: quay.io/minio/minio
    container_name: minio
    networks:
      kafka_network:
        ipv4_address: 172.20.0.6
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpassword
    command: server /data --console-address ":9001"

volumes:
  influxdb-data:
  minio-data:



