name: build router frr with nodeexporter
on:
  push:
    branches: [ main ]
    paths:
      - dockerImages/RouterFRRnodeexporter/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: dockerImages/RouterFRRnodeexporter
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/srv6-frr-nodeexporter:latest
            